### PR TITLE
New ompMC structure

### PR DESCRIPTION
**Pull request by edoerner**
This changes makes ompMC more 'modular', separating the code regarding the physics interactions for the geometry, source and scoring routines, which are located in the 'user codes'. Two user codes are offered, omc_dosxyz and omc_matrad, the later one corresponding to the ompMC module inside matRad.

### CODE REVIEW

**Comment by wahln** [comment]
Hi Edgardo, thanks again for the udpate! I think there is so far only one problem. For me, the code does not compile because the header defines the structures as "extern", and if they are declared threadprivate then, OpenMP throws an error. I can overcome this by a dirty hack using `#define extern` in the matrad interface... But I am not confident using this dirty stuff as a solution and want to look at other solutions first.

**Comment by edoerner** [comment]
EDIT: I think that I now really found the problem, the Visual Studio C++ compiler does not handle correctly the 'threadprivate' directive, as shown in this thread : https://stackoverflow.com/questions/12560243/using-threadprivate-directive-in-visual-studio

So I introduced a conditional compilation to handle this case if VS is used. I checked on two Windows machines with the VS2017 C++ compiler and the program compiles and runs fine. Good luck!

*****
Hi Niklas, I just updated the pull request, removing the #extern keyword from structures and leaving also their definitions in the header file. I tested this solution in my Windows machine using the Visual Studio 2017 compiler within mex and it works fine.

**Comment by wahln** [comment]
It seems like the new source/header files are not in git source controls (the repository only has the ompmc.c & ompmc.h files?

**Comment by edoerner** [comment]
my bad!, I just added the files xD

**Pull request merged**
